### ISSUE TITLE
Extension options UI in Firefox add-ons view looks unstyled/broken

### ISSUE THREAD

**Issue by mgol** [EFForg/https-everywhere#12485]
1. Open Firefox 55.0.3
2. Open the add-ons view with HTTPS Everywhere installed.
3. Click "More" in the HTTPS Everywhere row.
4. See unstyled UI that looks broken.

See the screenshot:
<img width="1877" alt="screen shot 2017-09-06 at 21 29 50" src="https://user-images.githubusercontent.com/1758366/30130748-8e0696b8-934a-11e7-8fb6-b6d181b596f1.png">

**Comment by foobar13373** [comment]
Can confirm. Additionally there's an odd behaviour: To get back to the add-ons list view, one has to click the back button _twice_. Seems like the initial page triggers some kind of reload to fetch the unstyled settings.

**Comment by jonathanKingston** [comment]
Here is a screenshot of the latest Nightly in Windows which has an incorrect background and checkbox that takes up the whole row:

![https-everywhere](https://user-images.githubusercontent.com/338988/30351902-6afeb428-9815-11e7-826b-ae298a36dce0.PNG)

**Comment by mgol** [comment]
The settings frame is unstyled in the Chrome version as well but since it's displayed there in a small dialog, it looks way better:
<img width="420" alt="screen shot 2017-09-07 at 16 16 36" src="https://user-images.githubusercontent.com/1758366/30541877-6b1948bc-9c7d-11e7-86d6-b77d60917a4d.png">

**Comment by koops76** [comment]
Maybe CSP blocks the styles from loading?

**Comment by koops76** [comment]
The problem is, there's no real styling being applied to anything in the window.

**Comment by koops76** [comment]
```css
.section-header{
  margin-bottom: 10px;
}

.section-header-span{
  border-bottom: 1px solid #ccc;
  font-size: 15px;
}

#import{
  margin-bottom: 10px;
  float: right;
}

#import-confirmed{
  display: none;
}
```
